main:
  - name: About
    url: '/about/aboutme'
    weight: 1
    
  - name: Projects
    url: /projects/
    weight: 2
    
  - name: Teaching
    url: /teaching/
    weight: 3 

    
  - name: Publications
    url: '/publications/publications'
 #   url: '#publications'
    weight: 5 
    
  - name: Posts
    url: /posts/
    weight: 4 
      