main:
  #- name: About
  #  url: '/about/aboutme'
  #  weight: 1
    
  - name: Projects
    url: /projects/
    weight: 1
    
  - name: Teaching
    url: /teaching/
    weight: 2 

  - name: Publications
    url: '/publications'
    weight: 4 
    
  - name: Posts
    url: /posts/
    weight: 3 
      
  - name: Contact
    url: '/contactme'
    weight: 6 
      